import http from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve('frontend/dist');const port=Number(process.env.PORT||3000);
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.json':'application/json; charset=utf-8'};
const headers={'x-content-type-options':'nosniff','referrer-policy':'no-referrer','permissions-policy':'camera=(), microphone=(), geolocation=()','content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'"};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url||'/','http://localhost');if(url.pathname==='/api/health'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store',...headers});res.end(JSON.stringify({ok:true,application:'ObligePay Edge Standalone',mode:'demo',liveData:false,wagering:false,payments:false,sharedAutoScoutAccounts:false,release:process.env.RAILWAY_GIT_COMMIT_SHA||'local'}));return;}if(url.pathname.startsWith('/api/')||!['GET','HEAD'].includes(req.method)){res.writeHead(501,{'content-type':'application/json','cache-control':'no-store',...headers});res.end(JSON.stringify({code:'STANDALONE_DEMO_ONLY',message:'No real accounts, payments, live feeds or wagering are enabled.'}));return;}let name=decodeURIComponent(url.pathname);const file=path.resolve(root,'.'+name);if(!file.startsWith(root+path.sep)&&file!==root){res.writeHead(403);res.end();return;}let target=file;try{if(!(await stat(target)).isFile())target=path.join(root,'index.html');}catch{if(path.extname(name)){res.writeHead(404,headers);res.end('Not found');return;}target=path.join(root,'index.html');}const body=await readFile(target);res.writeHead(200,{...headers,'content-type':types[path.extname(target)]||'application/octet-stream','cache-control':name.startsWith('/assets/')?'public,max-age=31536000,immutable':'no-cache','content-length':body.length});res.end(req.method==='HEAD'?undefined:body);}catch{res.writeHead(500,{'content-type':'text/plain',...headers});res.end('The standalone preview could not load this resource.');}});
server.listen(port,'0.0.0.0',()=>console.log(`EDGE_STANDALONE_READY port=${port} mode=demo wagering=false payments=false`));
process.on('SIGTERM',()=>server.close(()=>process.exit(0)));
