import {useState} from 'react';
import {Minus,Plus,RotateCcw,ChartNoAxesColumnIncreasing,Info} from 'lucide-react';
import {toast} from 'sonner';
import {type PlayerProp,propSelection} from '../data/samples';
import {summarize,type Side} from '../lib/domain';
import {useAppDispatch,useAppSelector,toggle} from '../store';
import {cn} from '../lib/utils';
import {Modal} from './UI';
export default function ResearchModal({prop,onClose}:{prop:PlayerProp;onClose:()=>void}){
 const [line,setLine]=useState(prop.line);const [side,setSide]=useState<Side>('OVER');const [window,setWindow]=useState(5);const dispatch=useAppDispatch();const selections=useAppSelector(s=>s.selections);const stats=summarize(prop.values.slice(-window),line,side);const max=Math.max(...prop.values,line,1)*1.18;
 return <Modal open title="Player research" onClose={onClose} wide><div className="research-player"><span className="player-avatar large">{prop.name.split(' ').map(s=>s[0]).join('')}</span><div><p className="eyebrow">{prop.sport} · SAMPLE ANALYSIS</p><h2>{prop.name}</h2><p>{prop.team} vs {prop.opponent} · {prop.stat}</p></div><ChartNoAxesColumnIncreasing className="text-emerald-400 ml-auto" size={29}/></div><div className="research-controls"><div><label>Analysis line</label><div className="line-stepper"><button disabled={line<=0} aria-label="Decrease research line" onClick={()=>setLine(n=>Math.max(0,n-.5))}><Minus size={17}/></button><strong data-testid="research-line">{line}</strong><button aria-label="Increase research line" onClick={()=>setLine(n=>Math.min(1000,n+.5))}><Plus size={17}/></button></div></div><div><label>Direction</label><div className="side-toggle">{(['OVER','UNDER'] as Side[]).map(s=><button key={s} aria-pressed={s===side} onClick={()=>setSide(s)} className={cn(side===s&&'active')}>{s}</button>)}</div></div></div><div className="research-stats"><div><span>Sample hit rate</span><b data-testid="research-rate">{stats.rate===null?'—':`${stats.rate}%`}</b></div><div><span>Sample average</span><b>{stats.average?.toFixed(1)??'—'}</b></div><div><span>Games / pushes</span><b>{stats.results.length} / {stats.pushes}</b></div></div><section className="chart-card"><div className="flex justify-between items-center gap-4"><h3>Recent sample results</h3><div className="market-tabs">{[5,10].map(n=><button key={n} className={cn('tab',window===n&&'active')} aria-pressed={window===n} onClick={()=>setWindow(n)}>L{n}</button>)}</div></div><svg viewBox="0 0 540 230" className="research-chart" role="img" aria-label={`${stats.hits} sample hits and ${stats.pushes} pushes against ${side.toLowerCase()} ${line}`}>
 {[0,1,2,3].map(i=><line key={i} x1="20" x2="525" y1={25+i*50} y2={25+i*50} stroke="#1e293b"/>)}
 {stats.results.map((r,i)=>{const unit=500/stats.results.length;const h=r.value/max*170;return <g key={i}><rect x={25+i*unit+unit*.19} width={unit*.62} y={190-h} height={h} rx="5" fill={r.result==='hit'?'#10b981':r.result==='push'?'#64748b':'#9b4656'}/><text x={25+i*unit+unit*.5} y={182-h} textAnchor="middle" fill="#cbd5e1" fontSize="11">{r.value}</text><text x={25+i*unit+unit*.5} y="212" textAnchor="middle" fill="#94a3b8" fontSize="10">G{i+1}</text></g>;})}<line x1="20" x2="525" y1={190-line/max*170} y2={190-line/max*170} stroke="#60a5fa" strokeDasharray="5 5"/><text x="522" y={184-line/max*170} fill="#93c5fd" fontSize="10" textAnchor="end">LINE {line}</text></svg><p>{stats.hits} hits · {stats.decisions-stats.hits} misses · {stats.pushes} pushes. Pushes are excluded from the hit-rate denominator.</p></section>{line!==prop.line&&<div className="calculation-warning"><Info size={16}/><span>This is a hypothetical line. The original sample price does not apply.<button onClick={()=>setLine(prop.line)} className="inline-flex items-center gap-1 text-emerald-400 ml-2"><RotateCcw size={12}/>Restore {prop.line}</button></span></div>}<button className="button primary w-full mt-5" disabled={line!==prop.line} onClick={()=>{const s=propSelection(prop,side);if(selections.length>=12&&!selections.some(x=>x.id===s.id)){toast.error('Maximum 12 sample selections.');return;}dispatch(toggle(s));toast('Demo selection updated');onClose();}}>Toggle {side.toLowerCase()} {prop.line} in demo slip</button><p className="fineprint mt-4">These results are fictional sample values, not actual player history or betting advice. No AI service is connected to this standalone preview.</p></Modal>;
}
