import {useState} from 'react';
import {useNavigate,useLocation,useSearchParams} from 'react-router-dom';
import {Activity,Trophy,Dribbble,Target,CalendarDays,ChevronDown,Search,Star,ArrowRight,ChartNoAxesColumnIncreasing,SlidersHorizontal,CircleDot,Goal} from 'lucide-react';
import {games,props,selectionFor,propSelection,type Game,type PlayerProp,type Market} from '../data/samples';
import {toggle,useAppDispatch,useAppSelector} from '../store';
import {formatOdds} from '../lib/domain';
import {cn} from '../lib/utils';
import {TeamMark,Empty} from './UI';
import {toast} from 'sonner';
const sports=[['NBA',Dribbble],['NFL',Trophy],['MLB',CircleDot],['NHL',Goal],['WNBA',Dribbble],['NCAAF',Trophy],['NCAAB',Target],['Soccer',Activity]] as const;
export default function SportsBoard({onResearch}:{onResearch:(p:PlayerProp)=>void}){
 const navigate=useNavigate();const loc=useLocation();const [params]=useSearchParams();const sport=loc.pathname==='/nfl'?'NFL':loc.pathname==='/nba'?'NBA':params.get('sport')||'NBA';
 const [query,setQuery]=useState('');const [group,setGroup]=useState('All games');const [book,setBook]=useState('ALL');const [stat,setStat]=useState('Popular');
 const dispatch=useAppDispatch();const selected=useAppSelector(s=>s.selections);
 const visibleGames=games.filter(g=>g.sport===sport&&(book==='ALL'||g.book===book)&&`${g.away} ${g.home} ${g.awayCode} ${g.homeCode}`.toLowerCase().includes(query.toLowerCase().trim()));
 const visibleProps=props.filter(p=>p.sport===sport&&(stat==='Popular'||p.stat===stat)&&`${p.name} ${p.team} ${p.opponent} ${p.stat}`.toLowerCase().includes(query.toLowerCase().trim()));
 const propStats=['Popular',...new Set(props.filter(p=>p.sport===sport).map(p=>p.stat))];
 const changeSport=(s:string)=>{setStat('Popular');setQuery('');navigate(s==='NBA'?'/nba':s==='NFL'?'/nfl':`/?sport=${encodeURIComponent(s)}`);};
 function choose(g:Game,m:Market){const s=selectionFor(g,m);if(selected.length>=12&&!selected.some(x=>x.id===s.id)){toast.error('The demo slip holds up to 12 selections.');return;}dispatch(toggle(s));}
 return <div className="space-y-5"><div className="sport-toolbar"><nav className="sports-tabs" aria-label="Sport filters">{sports.map(([s,Icon])=><button key={s} className={cn('sport-tab',sport===s&&'active')} aria-pressed={sport===s} onClick={()=>changeSport(s)}><Icon size={19}/>{s}</button>)}</nav><span className="slate-label"><CalendarDays size={16}/>Illustrative slate</span></div>
 <div className="hero-grid"><section className="hero"><div className="hero-content"><span className="eyebrow">A CLEARER VIEW OF THE GAME</span><h1>Smarter data.<br className="hero-break"/> Sharper decisions.</h1><p>Every market. Every angle. One focused workspace.</p><span className="hero-note"><span className="status-dot"/>Explore the interactive sample experience</span></div><div className="hero-art" aria-hidden="true"><svg viewBox="0 0 320 200"><defs><linearGradient id="court" x1="0" x2="1"><stop stopColor="#10b981" stopOpacity="0.08"/><stop offset="1" stopColor="#10b981" stopOpacity="0.7"/></linearGradient></defs><g fill="none" stroke="url(#court)" strokeWidth="1.5"><path d="M20 170 160 10l150 160H20ZM78 104h170M114 62h96M160 10v160"/><ellipse cx="160" cy="125" rx="61" ry="25"/><path d="M-10 190c160-180 270-160 340-140M-10 210C100 38 246 71 335 19"/><circle cx="250" cy="52" r="29"/><path d="M221 52h58M250 23v58M233 29c22 10 22 35 0 45M267 29c-22 10-22 35 0 45"/></g></svg></div></section><section className="angle-card panel"><p><Star size={17}/>Your sample slate</p><strong>{visibleGames.length.toString().padStart(2,'0')}</strong><div className="flex items-center justify-between gap-2"><span>Matchups to explore</span><button className="button outline compact" onClick={()=>document.getElementById('player-props')?.scrollIntoView({behavior:'smooth',block:'start'})}>Player props<ArrowRight size={14}/></button></div></section></div>
 <div className="board-toolbar"><label className="search-field"><Search size={18}/><input id="board-search" placeholder="Search teams, players, or matchups…" aria-label="Search teams or players" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="market-tabs">{['All games','Spread','Moneyline','Totals'].map(s=><button key={s} aria-pressed={group===s} onClick={()=>setGroup(s)} className={cn('tab',group===s&&'active')}>{s}</button>)}</div><label className="book-select"><SlidersHorizontal size={14}/><select aria-label="Sample bookmaker" value={book} onChange={e=>setBook(e.target.value)}><option value="ALL">All sample books</option><option value="A">Sample book A</option><option value="B">Sample book B</option></select><ChevronDown size={13}/></label></div>
 <section className="panel odds-board" aria-label="Sample odds board"><div className={cn('odds-heading',group!=='All games'&&'filtered')}><span>MATCHUP</span>{(group==='All games'?['Spread','Moneyline','Totals']:[group]).map(g=><span key={g}>{g.toUpperCase()}</span>)}<span className="text-right">SAMPLE</span></div>{visibleGames.map(g=><article key={g.id} className={cn('game-row',group!=='All games'&&'filtered')}><div className="matchup"><div className="matchup-teams"><div><TeamMark code={g.awayCode}/><span><b>{g.away}</b><small>vs {g.home}</small></span></div></div><span className="match-time">{g.time}<small>Sample book {g.book}</small></span></div>{(group==='All games'?['Spread','Moneyline','Totals']:[group]).map(gr=><div className="odds-pair" key={gr}><span className="mobile-market-label">{gr}</span>{g.markets.filter(m=>m.group===gr).map(m=>{const id=selectionFor(g,m).id;return <button key={id} className={cn('odds-cell',selected.some(s=>s.id===id)&&'selected')} onClick={()=>choose(g,m)} aria-label={`${g.awayCode} ${g.homeCode} ${m.label} ${formatOdds(m.price)}`} aria-pressed={selected.some(s=>s.id===id)}><b>{m.group==='Moneyline'?formatOdds(m.price):m.group==='Totals'?m.label.replace('Over','O').replace('Under','U'):m.label.split(' ').slice(1).join(' ')}</b><small>{m.group==='Moneyline'?m.label.split(' ')[0]:formatOdds(m.price)}</small></button>;})}</div>)}<span className="row-end"><ChartNoAxesColumnIncreasing size={17}/></span></article>)}{!visibleGames.length&&<Empty title="No matching sample games" body="This standalone preview has limited NBA, NFL and MLB sample coverage. These are not live listings." action="Show NBA samples" onAction={()=>{setBook('ALL');changeSport('NBA');}}/>}</section>
 <section className="panel props-panel" id="player-props" aria-label="Sample player props"><header className="props-header"><h2>Player Props</h2><div className="prop-tabs">{propStats.map(s=><button key={s} className={cn('tab',stat===s&&'active')} onClick={()=>setStat(s)} aria-pressed={stat===s}>{s}</button>)}</div><span className="sample-chip">SAMPLE DATA</span></header><div className="props-heading"><span>PLAYER</span><span>MATCHUP</span><span>LINE</span><span>OVER</span><span>UNDER</span><span>RESEARCH</span></div>{visibleProps.map(p=><div className="prop-row" key={p.id}><button className="player-identity" onClick={()=>onResearch(p)}><span className="player-avatar">{p.name.split(' ').map(s=>s[0]).join('')}</span><span><b>{p.name}</b><small>{p.team} · {p.sport}</small></span></button><span className="prop-match"><b>{p.team} @ {p.opponent}</b><small>{p.time} · sample</small></span><span className="prop-line"><b>{p.line}</b><small>{p.short}</small></span>{(['OVER','UNDER'] as const).map(side=>{const s=propSelection(p,side);return <button key={side} className={cn('odds-cell prop-odd',selected.some(x=>x.id===s.id)&&'selected')} aria-label={`${p.name} ${side} ${p.line}`} aria-pressed={selected.some(x=>x.id===s.id)} onClick={()=>{if(selected.length>=12&&!selected.some(x=>x.id===s.id)){toast.error('Maximum 12 demo selections.');return;}dispatch(toggle(s));}}><span className="mobile-market-label">{side}</span>{formatOdds(s.price)}</button>;})}<button className="analytics-link" aria-label={`Research ${p.name}`} onClick={()=>onResearch(p)}><ChartNoAxesColumnIncreasing size={17}/><span>Analytics</span></button></div>)}{!visibleProps.length&&<Empty title="No matching sample props" body="Try another sport, market or search. No live prop provider is connected to this app."/>}<footer className="panel-footer">All players, matchups, prices and results above are illustrative fixtures, not current sports information.</footer></section></div>;
}
