// Verified ESPN public team catalog, fetched 2026-09-20. Identity only; no runtime provider calls.
// Sources: https://site.api.espn.com/apis/site/v2/sports/{sport}/{league}/teams?limit=1000
// League paths: football/nfl, football/college-football, basketball/nba, basketball/wnba,
// basketball/mens-college-basketball, baseball/mlb, hockey/nhl, soccer/usa.1, soccer/eng.1, soccer/uefa.champions.
export const TEAM_IDENTITIES: Record<string, [string, string][]> = {
  "NFL": [
    ["ARI", "Arizona Cardinals"],
    ["ATL", "Atlanta Falcons"],
    ["BAL", "Baltimore Ravens"],
    ["BUF", "Buffalo Bills"],
    ["CAR", "Carolina Panthers"],
    ["CHI", "Chicago Bears"],
    ["CIN", "Cincinnati Bengals"],
    ["CLE", "Cleveland Browns"],
    ["DAL", "Dallas Cowboys"],
    ["DEN", "Denver Broncos"],
    ["DET", "Detroit Lions"],
    ["GB", "Green Bay Packers"],
    ["HOU", "Houston Texans"],
    ["IND", "Indianapolis Colts"],
    ["JAX", "Jacksonville Jaguars"],
    ["KC", "Kansas City Chiefs"],
    ["LAC", "Los Angeles Chargers"],
    ["LAR", "Los Angeles Rams"],
    ["LV", "Las Vegas Raiders"],
    ["MIA", "Miami Dolphins"],
    ["MIN", "Minnesota Vikings"],
    ["NE", "New England Patriots"],
    ["NO", "New Orleans Saints"],
    ["NYG", "New York Giants"],
    ["NYJ", "New York Jets"],
    ["PHI", "Philadelphia Eagles"],
    ["PIT", "Pittsburgh Steelers"],
    ["SEA", "Seattle Seahawks"],
    ["SF", "San Francisco 49ers"],
    ["TB", "Tampa Bay Buccaneers"],
    ["TEN", "Tennessee Titans"],
    ["WSH", "Washington Commanders"]
  ],
  "NBA": [
    ["ATL", "Atlanta Hawks"],
    ["BKN", "Brooklyn Nets"],
    ["BOS", "Boston Celtics"],
    ["CHA", "Charlotte Hornets"],
    ["CHI", "Chicago Bulls"],
    ["CLE", "Cleveland Cavaliers"],
    ["DAL", "Dallas Mavericks"],
    ["DEN", "Denver Nuggets"],
    ["DET", "Detroit Pistons"],
    ["GS", "Golden State Warriors"],
    ["HOU", "Houston Rockets"],
    ["IND", "Indiana Pacers"],
    ["LAC", "LA Clippers"],
    ["LAL", "Los Angeles Lakers"],
    ["MEM", "Memphis Grizzlies"],
    ["MIA", "Miami Heat"],
    ["MIL", "Milwaukee Bucks"],
    ["MIN", "Minnesota Timberwolves"],
    ["NO", "New Orleans Pelicans"],
    ["NY", "New York Knicks"],
    ["OKC", "Oklahoma City Thunder"],
    ["ORL", "Orlando Magic"],
    ["PHI", "Philadelphia 76ers"],
    ["PHX", "Phoenix Suns"],
    ["POR", "Portland Trail Blazers"],
    ["SA", "San Antonio Spurs"],
    ["SAC", "Sacramento Kings"],
    ["TOR", "Toronto Raptors"],
    ["UTAH", "Utah Jazz"],
    ["WSH", "Washington Wizards"]
  ],
  "WNBA": [
    ["ATL", "Atlanta Dream"],
    ["CHI", "Chicago Sky"],
    ["CON", "Connecticut Sun"],
    ["DAL", "Dallas Wings"],
    ["GS", "Golden State Valkyries"],
    ["IND", "Indiana Fever"],
    ["LA", "Los Angeles Sparks"],
    ["LV", "Las Vegas Aces"],
    ["MIN", "Minnesota Lynx"],
    ["NY", "New York Liberty"],
    ["PHX", "Phoenix Mercury"],
    ["POR", "Portland Fire"],
    ["SEA", "Seattle Storm"],
    ["TOR", "Toronto Tempo"],
    ["WSH", "Washington Mystics"]
  ],
  "MLB": [
    ["ARI", "Arizona Diamondbacks"],
    ["ATH", "Athletics"],
    ["ATL", "Atlanta Braves"],
    ["BAL", "Baltimore Orioles"],
    ["BOS", "Boston Red Sox"],
    ["CHC", "Chicago Cubs"],
    ["CHW", "Chicago White Sox"],
    ["CIN", "Cincinnati Reds"],
    ["CLE", "Cleveland Guardians"],
    ["COL", "Colorado Rockies"],
    ["DET", "Detroit Tigers"],
    ["HOU", "Houston Astros"],
    ["KC", "Kansas City Royals"],
    ["LAA", "Los Angeles Angels"],
    ["LAD", "Los Angeles Dodgers"],
    ["MIA", "Miami Marlins"],
    ["MIL", "Milwaukee Brewers"],
    ["MIN", "Minnesota Twins"],
    ["NYM", "New York Mets"],
    ["NYY", "New York Yankees"],
    ["PHI", "Philadelphia Phillies"],
    ["PIT", "Pittsburgh Pirates"],
    ["SD", "San Diego Padres"],
    ["SEA", "Seattle Mariners"],
    ["SF", "San Francisco Giants"],
    ["STL", "St. Louis Cardinals"],
    ["TB", "Tampa Bay Rays"],
    ["TEX", "Texas Rangers"],
    ["TOR", "Toronto Blue Jays"],
    ["WSH", "Washington Nationals"]
  ],
  "NHL": [
    ["ANA", "Anaheim Ducks"],
    ["BOS", "Boston Bruins"],
    ["BUF", "Buffalo Sabres"],
    ["CAR", "Carolina Hurricanes"],
    ["CBJ", "Columbus Blue Jackets"],
    ["CGY", "Calgary Flames"],
    ["CHI", "Chicago Blackhawks"],
    ["COL", "Colorado Avalanche"],
    ["DAL", "Dallas Stars"],
    ["DET", "Detroit Red Wings"],
    ["EDM", "Edmonton Oilers"],
    ["FLA", "Florida Panthers"],
    ["LA", "Los Angeles Kings"],
    ["MIN", "Minnesota Wild"],
    ["MTL", "Montreal Canadiens"],
    ["NJ", "New Jersey Devils"],
    ["NSH", "Nashville Predators"],
    ["NYI", "New York Islanders"],
    ["NYR", "New York Rangers"],
    ["OTT", "Ottawa Senators"],
    ["PHI", "Philadelphia Flyers"],
    ["PIT", "Pittsburgh Penguins"],
    ["SEA", "Seattle Kraken"],
    ["SJ", "San Jose Sharks"],
    ["STL", "St. Louis Blues"],
    ["TB", "Tampa Bay Lightning"],
    ["TOR", "Toronto Maple Leafs"],
    ["UTAH", "Utah Mammoth"],
    ["VAN", "Vancouver Canucks"],
    ["VGK", "Vegas Golden Knights"],
    ["WPG", "Winnipeg Jets"],
    ["WSH", "Washington Capitals"]
  ],
  "NCAAF": [
    ["AAMU", "Alabama A&M Bulldogs"],
    ["ABSU", "Albany State Golden Rams"],
    ["ACU", "Abilene Christian Wildcats"],
    ["ADR", "Adrian Bulldogs"],
    ["ADSU", "Adams State Grizzlies"],
    ["AF", "Air Force Falcons"],
    ["AFST", "Alfred State Pioneers"],
    ["AGSU", "Angelo State Rams"],
    ["AIC", "American International Yellow Jackets"],
    ["AKR", "Akron Zips"],
    ["ALA", "Alabama Crimson Tide"],
    ["ALBI", "Albion Britons"],
    ["ALBR", "Albright Lions"],
    ["ALCN", "Alcorn State Braves"],
    ["ALFR", "Alfred Saxons"],
    ["ALLG", "Allegheny Gators"],
    ["ALMA", "Alma Scots"],
    ["ALNU", "Allen Yellow Jackets"],
    ["ALST", "Alabama State Hornets"],
    ["ALVR", "Alvernia Golden Wolves"],
    ["AMH", "Amherst Mammoths"],
    ["AND", "Andrew Fighting Tigers"],
    ["ANIN", "Anderson (IN) Ravens"],
    ["ANSC", "Anderson (SC) Trojans"],
    ["APP", "App State Mountaineers"],
    ["APPRE", "Apprentice School Builders"],
    ["APSU", "Austin Peay Governors"],
    ["APU", "Azusa Pacific Cougars"],
    ["ARBA", "Arkansas Baptist Buffaloes"],
    ["ARIZ", "Arizona Wildcats"],
    ["ARK", "Arkansas Razorbacks"],
    ["ARMY", "Army Black Knights"],
    ["ARST", "Arkansas State Red Wolves"],
    ["ARTE", "Arkansas Tech Wonder Boys"],
    ["ASH", "Ashland Eagles"],
    ["ASP", "Assumption Greyhounds"],
    ["ASU", "Arizona State Sun Devils"],
    ["AUB", "Auburn Tigers"],
    ["AUGC", "Augustana (IL) Vikings"],
    ["AUGS", "Augsburg Auggies"],
    ["AUR", "Aurora Spartans"],
    ["AUS", "Austin 'Roos"],
    ["AUSD", "Augustana (SD) Vikings"],
    ["AVE M", "Ave Maria University Gyrenes"],
    ["AVER", "Averett Cougars"],
    ["AVILA", "Avila University Eagles"],
    ["AZCH", "Arizona Christian Firestorm"],
    ["BAK", "Baker University Baker"],
    ["BALL", "Ball State Cardinals"],
    ["BART", "Barton Bulldogs"],
    ["BATE", "Bates Bobcats"],
    ["BAY", "Baylor Bears"],
    ["BBM", "British Columbia British Col"],
    ["BBU", "Bloomsburg Huskies"],
    ["BC", "Boston College Eagles"],
    ["BCU", "Bethune-Cookman Wildcats"],
    ["BCWV", "Bethany (WV) Bison"],
    ["BELH", "Belhaven Blazers"],
    ["BELO", "Beloit Buccaneers"],
    ["BEN", "Benedict Tigers"],
    ["BENC", "Benedictine College Ravens"],
    ["BENT", "Bentley Falcons"],
    ["BERR", "Berry Vikings"],
    ["BGSU", "Bowling Green Falcons"],
    ["BHSU", "Black Hills State Yellow Jackets"],
    ["BLF", "Bluffton Beavers"],
    ["BLU", "BLUEFIELD Ramblin' Rams"],
    ["BLUS", "Bluefield State Big Blue"],
    ["BNIL", "Benedictine (IL) Eagles"],
    ["BOIS", "Boise State Broncos"],
    ["BOW", "Bowdoin Polar Bears"],
    ["BOWE", "Bowie State Bulldogs"],
    ["BRE", "Brevard Tornados"],
    ["BRI", "Bridgewater Eagles"],
    ["BRIS", "Bridgewater State Bears"],
    ["BRO", "Brockport Golden Eagles"],
    ["BRWN", "Brown Bears"],
    ["BRY", "Bryant Bulldogs"],
    ["BST", "Bemidji State Beavers"],
    ["BSU", "Buffalo State Bengals"],
    ["BTLR", "Butler Bulldogs"],
    ["BTTN", "Bethel (TN) Wildcats"],
    ["BUCK", "Bucknell Bison"],
    ["BUF", "Buffalo Bulls"],
    ["BUMN", "Bethel (MN) Royals"],
    ["BVU", "Buena Vista Beavers"],
    ["BW", "Baldwin Wallace Yellow Jackets"],
    ["BYKS", "Bethany (KS) Swedes"],
    ["BYU", "BYU Cougars"],
    ["CAL", "California Golden Bears"],
    ["CALU", "Calvin Knights"],
    ["CAM", "Campbell Fighting Camels"],
    ["CAPA", "California (PA) Vulcans"],
    ["CAPU", "Capital Comets"],
    ["CAR", "Carleton Knights"],
    ["CARK", "Central Arkansas Bears"],
    ["CAT", "Catawba Indians"],
    ["CATH", "Catholic Cardinals"],
    ["CBVU", "Campbellsville Tigers"],
    ["CC", "Curry Colonels"],
    ["CCMN", "Concordia (MN) Cobbers"],
    ["CCO", "Centre Colonels"],
    ["CCSU", "Central Connecticut Blue Devils"],
    ["CCU", "Coastal Carolina Chanticleers"],
    ["CCW", "Carthage Firebirds"],
    ["CDF", "Central Methodist Eagles"],
    ["CGMU", "Carnegie Mellon Tartans"],
    ["CHAD", "Chadron State Eagles"],
    ["CHAP", "Chapman Panthers"],
    ["CHI", "Chicago Maroons"],
    ["CHSO", "Charleston Southern Buccaneers"],
    ["CHST", "Chicago State Cougars"],
    ["CIN", "Cincinnati Bearcats"],
    ["CIT", "The Citadel Bulldogs"],
    ["CKGA", "Clark Atlanta Panthers"],
    ["CLBY", "Colby White Mules"],
    ["CLEM", "Clemson Tigers"],
    ["CLRN", "Clarion Golden Eagles"],
    ["CLT", "Charlotte 49ers"],
    ["CLU", "Cal Lutheran Kingsmen"],
    ["CMBS", "Cumberlands Indians"],
    ["CMIN", "Colorado School of Mines Orediggers"],
    ["CMS", "Claremont Mudd Scripps Stags"],
    ["CMU", "Central Michigan Chippewas"],
    ["CN", "Carson Newman Eagles"],
    ["CNIA", "Cornell (IA) Rams"],
    ["CNSU", "Central State Marauders"],
    ["CNTC", "Central College Dutch"],
    ["CNU", "Christopher Newport Captains"],
    ["COE", "Coe Kohawks"],
    ["COI", "College of Idaho Yotes"],
    ["COLE", "Cole College Jaguars"],
    ["COLG", "Colgate Raiders"],
    ["COLLE", "Charlotte Saints"],
    ["COLO", "Colorado Buffaloes"],
    ["COLU", "Columbia Lions"],
    ["COMU", "Colorado Mesa Mavericks"],
    ["CONC", "Concord Mountain Lions"],
    ["CONCMI", "Concordia-Michigan Cardinals"],
    ["CONCONE", "Concordia University Nebraska Clippers"],
    ["CONN", "UConn Huskies"],
    ["COR", "Cornell Big Red"],
    ["CP", "Cal Poly Mustangs"],
    ["CRU", "Carroll (WI) Pioneers"],
    ["CRWN", "Crown Polars"],
    ["CSP", "Concordia St. Paul Golden Bears"],
    ["CSS", "St. Scholastica Saints"],
    ["CSU", "Colorado State Rams"],
    ["CSUP", "CSU Pueblo ThunderWolves"],
    ["CTLA", "Centenary (LA) Gentlemen"],
    ["CUC", "Concordia Chicago Cougars"],
    ["CULVE", "Culver-Stockton College Wildcats"],
    ["CUMBTN", "Cumberland (TN) Bulldogs"],
    ["CUW", "Concordia (WI) Falcons"],
    ["CWAN", "Chowan Hawks"],
    ["CWAU", "Central Washington Wildcats"],
    ["CWRU", "Case Western Reserve Spartans"],
    ["DAKOT", "Dakota State University Trojans"],
    ["DART", "Dartmouth Big Green"],
    ["DAV", "Davidson Wildcats"],
    ["DAY", "Dayton Flyers"],
    ["DBQ", "Dubuque Spartans"],
    ["DEAN", "Dean Bulldogs"],
    ["DEF", "Defiance College Yellow Jackets"],
    ["DEL", "Delaware Blue Hens"],
    ["DIC", "Dickinson State University Blue Hawks"],
    ["DKSN", "Dickinson Red Devils"],
    ["DLST", "Delta State Statesmen"],
    ["DPU", "DePauw Tigers"],
    ["DRKE", "Drake Bulldogs"],
    ["DSN", "Denison Big Red"],
    ["DSU", "Delaware State Hornets"],
    ["DUKE", "Duke Blue Devils"],
    ["DUQ", "Duquesne Dukes"],
    ["DVU", "Delaware Valley Aggies"],
    ["DWU", "Dakota Wesleyan Tigers"],
    ["ECNU", "East Central Tigers"],
    ["ECSU", "Elizabeth City State Vikings"],
    ["ECU", "East Carolina Pirates"],
    ["EDBR", "Edinboro Fighting Scots"],
    ["EDW", "Edward Waters Tigers"],
    ["EHC", "Emory & Henry Wasps"],
    ["EIU", "Eastern Illinois Panthers"],
    ["EKU", "Eastern Kentucky Colonels"],
    ["ELMH", "Elmhurst Bluejays"],
    ["ELON", "Elon Phoenix"],
    ["EMSU", "Emporia State Hornets"],
    ["EMU", "Eastern Michigan Eagles"],
    ["ENDC", "Endicott Gulls"],
    ["ENMU", "Eastern New Mexico Greyhounds"],
    ["EORE", "Eastern Oregon"],
    ["ERKA", "Eureka Red Devils"],
    ["ERSK", "Erskine Flying Fleet"],
    ["ESU", "East Stroudsburg Warriors"],
    ["ETAM", "East Texas A&M Lions"],
    ["ETBU", "East Texas Baptist Tigers"],
    ["ETSU", "East Tennessee State Buccaneers"],
    ["EU", "Eastern Eagles"],
    ["EVA", "Evangel University Crusaders"],
    ["EWU", "Eastern Washington Eagles"],
    ["FAI", "West Memphis Crusaders"],
    ["FAMU", "Florida A&M Rattlers"],
    ["FAU", "Florida Atlantic Owls"],
    ["FAULKNER", "Faulkner University Eagles"],
    ["FAYU", "Fayetteville State Broncos"],
    ["FBSU", "Fitchburg State Falcons"],
    ["FC", "Ferrum Panthers"],
    ["FDUF", "FDU Florham Devils"],
    ["FHSU", "Fort Hays Tigers"],
    ["FIU", "Florida International Panthers"],
    ["FLA", "Florida Gators"],
    ["FLWC", "Fort Lewis Skyhawks"],
    ["FMC", "Franklin & Marshall Diplomats"],
    ["FMSU", "Fairmont State Falcons"],
    ["FMU", "Florida Memorial Lions"],
    ["FOR", "Fordham Rams"],
    ["FP", "Franklin Pierce Ravens"],
    ["FRES", "Fresno State Bulldogs"],
    ["FRIE", "Friends University Friends"],
    ["FRKL", "Franklin Grizzlies"],
    ["FRST", "Ferris State Bulldogs"],
    ["FRSU", "Framingham State Rams"],
    ["FSTU", "Frostburg State Bobcats"],
    ["FSU", "Florida State Seminoles"],
    ["FUR", "Furman Paladins"],
    ["FVSU", "Fort Valley State Wildcats"],
    ["GAC", "Gustavus Adolphus Golden Gusties"],
    ["GANN", "Gannon Golden Knights"],
    ["GASO", "Georgia Southern Eagles"],
    ["GAST", "Georgia State Panthers"],
    ["GEN", "Geneva Golden Tornadoes"],
    ["GFU", "George Fox Bruins"],
    ["GLDT", "Gallaudet Bison"],
    ["GLFD", "Guilford Quakers"],
    ["GMU", "George Mason University Patriots"],
    ["GRAM", "Grambling Tigers"],
    ["GRANDVIEW", "Des Moines Vikings"],
    ["GRC", "Graceland University Graceland"],
    ["GRNB", "Greensboro Pride"],
    ["GRNL", "Grinnell Pioneers"],
    ["GRNV", "Greenville Panthers"],
    ["GRO", "Grove City Wolverines"],
    ["GT", "Georgia Tech Yellow Jackets"],
    ["GTKY", "Georgetown (KY) Tigers"],
    ["GTWN", "Georgetown Hoyas"],
    ["GTYB", "Gettysburg Bullets"],
    ["GVLS", "Glenville State Pioneers"],
    ["GVSU", "Grand Valley State Lakers"],
    ["GWEB", "Gardner-Webb Runnin' Bulldogs"],
    ["HAM", "Hamilton Continentals"],
    ["HAMP", "Hampton Pirates"],
    ["HARD", "Harding Bisons"],
    ["HARV", "Harvard Crimson"],
    ["HASKELL", "Haskell Indian Nations Univ Jayhawks"],
    ["HAW", "Hawai'i Rainbow Warriors"],
    ["HBRT", "Hobart Statesmen"],
    ["HC", "Holy Cross Crusaders"],
    ["HCU", "Houston Christian Huskies"],
    ["HDBG", "Heidelberg Student Princes"],
    ["HDX", "Hendrix Warriors"],
    ["HIRM", "Hiram Terriers"],
    ["HLBT", "Hilbert Hawks"],
    ["HLDL", "Hillsdale Chargers"],
    ["HMLN", "Hamline Pipers"],
    ["HNTC", "Huntingdon Hawks"],
    ["HNVR", "Hanover Panthers"],
    ["HOL", "Holland College Hurricanes"],
    ["HOPE", "Hope Flying Dutchmen"],
    ["HOU", "Houston Cougars"],
    ["HOW", "Howard Bison"],
    ["HRTW", "Hartwick Hawks"],
    ["HSC", "Hampden Sydney Tigers"],
    ["HSTU", "Henderson State Reddies"],
    ["HSU", "Hardin Simmons Cowboys"],
    ["HUSS", "Husson Eagles"],
    ["HVCC", "Troy Vikings"],
    ["HWPU", "Howard Payne Yellow Jackets"],
    ["IDHO", "Idaho Vandals"],
    ["IDST", "Idaho State Bengals"],
    ["ILL", "Illinois Fighting Illini"],
    ["ILLC", "Illinois College Blueboys"],
    ["ILST", "Illinois State Redbirds"],
    ["ILWU", "Illinois Wesleyan Titans"],
    ["INDY", "Indianapolis Greyhounds"],
    ["INST", "Indiana State Sycamores"],
    ["INWESL", "Indiana Wesleyan Wildcats"],
    ["IOWA", "Iowa Hawkeyes"],
    ["ISU", "Iowa State Cyclones"],
    ["ITH", "Ithaca Bombers"],
    ["IU", "Indiana Hoosiers"],
    ["IUP", "IU Pennsylvania Crimson Hawks"],
    ["JCSU", "Johnson C. Smith Golden Bulls"],
    ["JCU", "John Carroll Blue Streaks"],
    ["JHU", "Johns Hopkins Blue Jays"],
    ["JKST", "Jackson State Tigers"],
    ["JMU", "James Madison Dukes"],
    ["JUDSO", "Elgin Eagles"],
    ["JUN", "Juniata Eagles"],
    ["JXST", "Jacksonville State Gamecocks"],
    ["KALC", "Kalamazoo Hornets"],
    ["KANSA", "Kansas Wesleyan Ks Wesleyan"],
    ["KEAN", "Kean Cougars"],
    ["KEISER", "Keiser University Keiser"],
    ["KENN", "Kennesaw State Owls"],
    ["KENT", "Kent State Golden Flashes"],
    ["KNGS", "King's Monarchs"],
    ["KNOX", "Knox Prairie Fire"],
    ["KNY", "Kenyon Owls"],
    ["KSU", "Kansas State Wildcats"],
    ["KU", "Kansas Jayhawks"],
    ["KUTZ", "Kutztown Golden Bears"],
    ["KWC", "Kentucky Wesleyan Panthers"],
    ["KYCHR", "Kentucky Christian Knights"],
    ["KYSN", "Keystone Giants"],
    ["KYSU", "Kentucky State Thorobreds"],
    ["LAF", "Lafayette Leopards"],
    ["LAM", "Lamar Cardinals"],
    ["LANE", "Lane College Dragons"],
    ["LAW", "Lawrence Vikings"],
    ["LC", "Lewis & Clark River Otters"],
    ["LCHR", "Louisiana Christian Wildcats"],
    ["LEH", "Lehigh Mountain Hawks"],
    ["LENR", "Lenoir Rhyne Bears"],
    ["LFC", "Lake Forest Foresters"],
    ["LGC", "LaGrange Panthers"],
    ["LHU", "Lock Haven Bald Eagles"],
    ["LIB", "Liberty Flames"],
    ["LIN", "Lindenwood Lions"],
    ["LINB", "Lindenwood Belleville Lynx"],
    ["LINF", "Linfield Wildcats"],
    ["LIU", "Long Island University Sharks"],
    ["LIV", "Livingstone Blue Bears"],
    ["LKER", "Lake Erie Storm"],
    ["LKLD", "Lakeland Muskies"],
    ["LNCA", "Lincoln (CA) Oaklanders"],
    ["LNGT", "Langston Lions"],
    ["LNMO", "Lincoln (MO) Blue Tigers"],
    ["LNPA", "Lincoln (PA) Lions"],
    ["LOR", "Loras Duhawks"],
    ["LOU", "Louisville Cardinals"],
    ["LSU", "LSU Tigers"],
    ["LT", "Louisiana Tech Bulldogs"],
    ["LUTH", "Luther Norse"],
    ["LVC", "Lebanon Valley Flying Dutchmen"],
    ["LWU", "Lindsey Wilson LINDSEY"],
    ["LYCO", "Lycoming Warriors"],
    ["LYON", "Lyon Scots"],
    ["M-OH", "Miami (OH) RedHawks"],
    ["MAC", "Macalester Scots"],
    ["MARY", "University of Mary Marauders"],
    ["MASS", "Massachusetts Minutemen"],
    ["MB", "MANITOBA"],
    ["MCD", "McDaniel Green Terror"],
    ["MCK", "McKendree Bearcats"],
    ["MCM", "McMurry War Hawks"],
    ["MCN", "McNeese Cowboys"],
    ["MCST", "Montclair State Red Hawks"],
    ["MCTN", "Maryville (TN) Scots"],
    ["MD", "Maryland Terrapins"],
    ["MDAR", "UMass Dartmouth Corsairs"],
    ["MDNN", "MADONNA"],
    ["ME", "Maine Black Bears"],
    ["MEM", "Memphis Tigers"],
    ["MER", "Mercer Bears"],
    ["MERC", "Mercyhurst Lakers"],
    ["MHB", "Mary Hardin Baylor Crusaders"],
    ["MHU", "Mars Hill Lions"],
    ["MIA", "Miami Hurricanes"],
    ["MICH", "Michigan Wolverines"],
    ["MIDB", "Middlebury Panthers"],
    ["MIDL", "Midland MIDLAND LUTHERAN"],
    ["MILE", "Miles Golden Bears"],
    ["MILK", "Millikin Big Blue"],
    ["MILL", "Millersville Marauders"],
    ["MINN", "Minnesota Golden Gophers"],
    ["MINS", "Minot State Beavers"],
    ["MISE", "Misericordia Cougars"],
    ["MISS", "Ole Miss Rebels"],
    ["MIT", "MIT Engineers"],
    ["MITE", "Monterrey Tech Borregos"],
    ["MIZ", "Missouri Tigers"],
    ["MLC", "Martin Luther Knights"],
    ["MLSP", "Millsaps Majors"],
    ["MMA", "Merchant Marine Mariners"],
    ["MMT", "Mass Maritime Buccaneers"],
    ["MNCH", "Manchester Spartans"],
    ["MNFD", "Mansfield Mountaineers"],
    ["MNGS", "Morningside Chiefs"],
    ["MNIL", "Monmouth (IL) Fighting Scots"],
    ["MNMO", "Minnesota Morris Cougars"],
    ["MNST", "Minnesota State Mavericks"],
    ["MOBU", "Missouri Baptist Spartans"],
    ["MON", "Monroe Mustangs"],
    ["MONM", "Monmouth Hawks"],
    ["MONT", "Montana Grizzlies"],
    ["MOR", "Moravian Greyhounds"],
    ["MORE", "Morehead State Eagles"],
    ["MORG", "Morgan State Bears"],
    ["MOST", "Missouri State Bears"],
    ["MOWE", "Missouri Western Griffons"],
    ["MRHO", "Morehouse Maroon Tigers"],
    ["MRMK", "Merrimack Warriors"],
    ["MRSH", "Marshall Thundering Herd"],
    ["MRST", "Marist Red Foxes"],
    ["MRTT", "Marietta Pioneers"],
    ["MS&T", "Missouri S&T Miners"],
    ["MSJ", "Mount St Joseph Lions"],
    ["MSK", "Muskingum Fighting Muskies"],
    ["MSST", "Mississippi State Bulldogs"],
    ["MSSU", "Missouri Southern State Lions"],
    ["MSU", "Michigan State Spartans"],
    ["MSUM", "Minnesota St Moorhead Dragons"],
    ["MTST", "Montana State Bobcats"],
    ["MTSU", "Middle Tennessee Blue Raiders"],
    ["MTU", "Michigan Tech Huskies"],
    ["MU", "Methodist Monarchs"],
    ["MUHL", "Muhlenberg Mules"],
    ["MUIN", "Marian (IN) MARIAN"],
    ["MUR", "Murray State Racers"],
    ["MVSU", "Mississippi Valley State Delta Devils"],
    ["MWMO", "Northwest Missouri State Bearcats"],
    ["MWSU", "Midwestern State Mustangs"],
    ["MYSU", "Mayville State Comets"],
    ["NAMU", "North American Stallions"],
    ["NAU", "Northern Arizona Lumberjacks"],
    ["NAVY", "Navy Midshipmen"],
    ["NBRY", "Newberry Wolves"],
    ["NCAT", "North Carolina A&T Aggies"],
    ["NCC", "North Central College Cardinals"],
    ["NCCU", "North Carolina Central Eagles"],
    ["NCSU", "NC State Wolfpack"],
    ["NCW", "North Carolina Wesleyan Battling Bishops"],
    ["ND", "Notre Dame Fighting Irish"],
    ["NDSU", "North Dakota State Bison"],
    ["NEB", "Nebraska Cornhuskers"],
    ["NEBK", "Nebraska Kearney Lopers"],
    ["NEL", "Nelson (TX) Lions"],
    ["NESU", "Northeastern State RiverHawks"],
    ["NEV", "Nevada Wolf Pack"],
    ["NGU", "North Greenville Trailblazers"],
    ["NHVN", "New Haven Chargers"],
    ["NICC", "Nichols Bison"],
    ["NICH", "Nicholls Colonels"],
    ["NIU", "Northern Illinois Huskies"],
    ["NMHU", "New Mexico Highlands Cowboys"],
    ["NMI", "Northern Michigan Wildcats"],
    ["NMSU", "New Mexico State Aggies"],
    ["NORF", "Norfolk State Spartans"],
    ["NPU", "North Park Vikings"],
    ["NSU", "Northern State Wolves"],
    ["NU", "Northwestern Wildcats"],
    ["NWCH", "Norwich Cadets"],
    ["NWD", "Northwood Timberwolves"],
    ["NWOK", "Northwestern (OK) Rangers"],
    ["NWST", "Northwestern State Demons"],
    ["NWU", "Nebraska Wesleyan Prairie Wolves"],
    ["NYCL", "SUNY Cortland Red Dragons"],
    ["NYER", "SUNY Erie Kats"],
    ["NYMS", "SUNY Morrisville Mustangs"],
    ["NYMT", "SUNY Maritime Privateers"],
    ["OBE", "Oberlin Yeomen"],
    ["OBU", "Ouachita Baptist Tigers"],
    ["ODU", "Old Dominion Monarchs"],
    ["OHDU", "Ohio Dominican Panthers"],
    ["OHIO", "Ohio Bobcats"],
    ["OHNU", "Ohio Northern Polar Bears"],
    ["OKBU", "Oklahoma Baptist Bison"],
    ["OKST", "Oklahoma State Cowboys"],
    ["OLAF", "St. Olaf Oles"],
    ["OPSU", "Oklahoma Panhandle OK PANHANDLE ST"],
    ["ORE", "Oregon Ducks"],
    ["ORST", "Oregon State Beavers"],
    ["OSU", "Ohio State Buckeyes"],
    ["OSU", "Ohio State Newark Titans"],
    ["OTTB", "Otterbein Cardinals"],
    ["OU", "Oklahoma Sooners"],
    ["OWU", "Ohio Wesleyan Battling Bishops"],
    ["PACE", "Pace Setters"],
    ["PCLT", "Pacific Lutheran Lutes"],
    ["PCOR", "Pacific (OR) Boxers"],
    ["PENN", "Pennsylvania Quakers"],
    ["PIKEV", "Pikeville Bears"],
    ["PITT", "Pittsburgh Panthers"],
    ["PLYM", "Plymouth State Panthers"],
    ["POINT", "Point University Skyhawks"],
    ["POPI", "Pomona Pitzer Sagehens"],
    ["POST", "Post Eagles"],
    ["PRES", "Presbyterian Blue Hose"],
    ["PRIN", "Princeton Tigers"],
    ["PRST", "Portland State Vikings"],
    ["PSU", "Penn State Nittany Lions"],
    ["PTSU", "Pittsburg State Gorillas"],
    ["PUG", "Puget Sound Loggers"],
    ["PUR", "Purdue Boilermakers"],
    ["PV", "Prairie View A&M Panthers"],
    ["QUI", "Quincy Hawks"],
    ["REDL", "Redlands Bulldogs"],
    ["RFU", "Rockford Regents"],
    ["RHDS", "Rhodes Lynx"],
    ["RHDT", "Reinhardt Eagles"],
    ["RHIT", "Rose Hulman Fightin' Engineers"],
    ["RICE", "Rice Owls"],
    ["RICH", "Richmond Spiders"],
    ["RIP", "Ripon Red Hawks"],
    ["RMC", "Randolph Macon Yellow Jackets"],
    ["RMU", "Robert Morris Colonials"],
    ["ROW", "Rowan Profs"],
    ["RPI", "Rensselaer Engineers"],
    ["RSVT", "Roosevelt Lakers"],
    ["RUTG", "Rutgers Scarlet Knights"],
    ["SAC", "Sacramento State Hornets"],
    ["SAL", "Salisbury Sea Gulls"],
    ["SALV", "Salve Regina Seahawks"],
    ["SAM", "Samford Bulldogs"],
    ["SANS", "Saint Anselm Hawks"],
    ["SAR", "Southern Arkansas Muleriders"],
    ["SAV", "Savannah State Tigers"],
    ["SC", "South Carolina Gamecocks"],
    ["SCIA", "Simpson (IA) Storm"],
    ["SCST", "South Carolina State Bulldogs"],
    ["SCTS", "Southern Connecticut State Owls"],
    ["SDAK", "South Dakota Coyotes"],
    ["SDMT", "South Dakota Mines Hardrockers"],
    ["SDST", "South Dakota State Jackrabbits"],
    ["SDSU", "San Diego State Aztecs"],
    ["SEHI", "Seton Hill Griffins"],
    ["SELA", "SE Louisiana Lions"],
    ["SEMO", "Southeast Missouri State Redhawks"],
    ["SEOK", "Southeastern Oklahoma State Savage Storm"],
    ["SEU", "Southeastern Fires"],
    ["SEWA", "Sewanee Tigers"],
    ["SFA", "Stephen F. Austin Lumberjacks"],
    ["SFIL", "St. Francis (IL) Fighting Saints"],
    ["SFIN", "Saint Francis (IN) Cougars"],
    ["SFPA", "Saint Francis Red Flash"],
    ["SFU", "Sioux Falls Cougars"],
    ["SHAW", "Shaw Bears"],
    ["SHEN", "Shenandoah Hornets"],
    ["SHEP", "Shepherd Rams"],
    ["SHIP", "Shippensburg Raiders"],
    ["SHOU", "Shorter Hawks"],
    ["SHSU", "Sam Houston Bearkats"],
    ["SHTU", "Siena Heights Saints"],
    ["SHU", "Sacred Heart Pioneers"],
    ["SIU", "Southern Illinois Salukis"],
    ["SJSU", "San José State Spartans"],
    ["SMU", "SMU Mustangs"],
    ["SNU", "Southern Nazarene Crimson Storm"],
    ["SOR", "Southern Oregon Raiders"],
    ["SOSU", "Southwestern Oklahoma State Bulldogs"],
    ["SOU", "Southern Jaguars"],
    ["SOVA", "Southern Virginia Knights"],
    ["SPR", "Springfield Pride"],
    ["SRST", "Sul Ross State Lobos"],
    ["SRU", "Slippery Rock The Rock"],
    ["STAM", "St. Ambrose Fighting Bees"],
    ["STAN", "Stanford Cardinal"],
    ["STAU", "St. Andrews Knights"],
    ["STBK", "Stony Brook Seawolves"],
    ["STET", "Stetson Hatters"],
    ["STJF", "St. John Fisher Cardinals"],
    ["STJM", "Saint John's (MN) Johnnies"],
    ["STLG", "Sterling STERLING KS"],
    ["STMN", "St. Thomas Tommies"],
    ["STNC", "St. Norbert Green Knights"],
    ["STO", "Stonehill Skyhawks"],
    ["STVS", "Stevenson Mustangs"],
    ["STX", "Saint Xavier Cougars"],
    ["SUCA", "Simpson (CA) Red Hawks"],
    ["SUSQ", "Susquehanna River Hawks"],
    ["SUU", "Southern Utah Thunderbirds"],
    ["SVC", "Saint Vincent Bearcats"],
    ["SVSU", "Saginaw Valley State Cardinals"],
    ["SWBU", "Southwest Baptist Bearcats"],
    ["SWKS", "Southwestern (KS) Moundbuilders"],
    ["SWMS", "Southwest Minnesota State Mustangs"],
    ["SWU", "Southwestern U Pirates"],
    ["SYR", "Syracuse Orange"],
    ["TA&M", "Texas A&M Aggies"],
    ["TAMK", "Texas A&M-Kingsville Javelinas"],
    ["TAR", "Tarleton State Texans"],
    ["TBIB", "Trinity Bible Lions"],
    ["TCCT", "Trinity (CT) Bantams"],
    ["TCNJ", "The College of New Jersey Lions"],
    ["TCU", "TCU Horned Frogs"],
    ["TEM", "Temple Owls"],
    ["TENN", "Tennessee Volunteers"],
    ["TEX", "Texas Longhorns"],
    ["THI", "Thiel Tomcats"],
    ["THO", "Thomas Night Hawks"],
    ["TIFF", "Tiffin Dragons"],
    ["TLRU", "Taylor Trojans"],
    ["TLSA", "Tulsa Golden Hurricane"],
    ["TMOR", "Thomas More Saints"],
    ["TNST", "Tennessee State Tigers"],
    ["TNTC", "Tennessee Tech Golden Eagles"],
    ["TOL", "Toledo Rockets"],
    ["TOW", "Towson Tigers"],
    ["TRNE", "Trine Thunder"],
    ["TROY", "Troy Trojans"],
    ["TRST", "Truman State Bulldogs"],
    ["TTU", "Texas Tech Red Raiders"],
    ["TUFT", "Tufts Jumbos"],
    ["TULN", "Tulane Green Wave"],
    ["TUSC", "Tusculum Pioneers"],
    ["TUSK", "Tuskegee Golden Tigers"],
    ["TUTX", "Trinity (TX) Tigers"],
    ["TXCL", "Texas College Steers"],
    ["TXLU", "Texas Lutheran Bulldogs"],
    ["TXSO", "Texas Southern Tigers"],
    ["TXST", "Texas State Bobcats"],
    ["UAB", "UAB Blazers"],
    ["UALB", "UAlbany Great Danes"],
    ["UAM", "Arkansas Monticello Boll Weevils"],
    ["UAPB", "Arkansas-Pine Bluff Golden Lions"],
    ["UCD", "UC Davis Aggies"],
    ["UCF", "UCF Knights"],
    ["UCLA", "UCLA Bruins"],
    ["UCM", "Central Missouri Mules"],
    ["UCO", "Central Oklahoma Bronchos"],
    ["UCWV", "Charleston (WV) Golden Eagles"],
    ["UF", "Findlay Oilers"],
    ["UFFL", "St. Petersburg Glory Eagles"],
    ["UGA", "Georgia Bulldogs"],
    ["UIU", "Upper Iowa Peacocks"],
    ["UIW", "Incarnate Word Cardinals"],
    ["UJ", "Jamestown Jimmies"],
    ["UK", "Kentucky Wildcats"],
    ["UL", "Louisiana Ragin' Cajuns"],
    ["ULM", "UL Monroe Warhawks"],
    ["ULV", "La Verne Leopards"],
    ["UMD", "Minnesota Duluth Bulldogs"],
    ["UMMA", "Maine Maritime Mariners"],
    ["UMU", "Mount Union Purple Raiders"],
    ["UMW", "Montana Western Bulldogs"],
    ["UNA", "North Alabama Lions"],
    ["UNAM", "University of Mexico MEXICO U"],
    ["UNC", "North Carolina Tar Heels"],
    ["UNCO", "Northern Colorado Bears"],
    ["UNCP", "UNC Pembroke Braves"],
    ["UND", "North Dakota Fighting Hawks"],
    ["UNE", "New England Nor'easters"],
    ["UNH", "New Hampshire Wildcats"],
    ["UNI", "Northern Iowa Panthers"],
    ["UNLV", "UNLV Rebels"],
    ["UNM", "New Mexico Lobos"],
    ["UNNY", "Union Garnet Chargers"],
    ["UNT", "North Texas Mean Green"],
    ["UNW", "Northwestern (MN) Eagles"],
    ["UOO", "Olivet Comets"],
    ["URI", "Rhode Island Rams"],
    ["URNY", "Rochester (NY) Yellow Jackets"],
    ["URSN", "Ursinus Bears"],
    ["USA", "South Alabama Jaguars"],
    ["USC", "USC Trojans"],
    ["USCG", "Coast Guard Bears"],
    ["USD", "San Diego Toreros"],
    ["USF", "South Florida Bulls"],
    ["USL", "St. Lawrence Saints"],
    ["USM", "Southern Miss Golden Eagles"],
    ["USU", "Utah State Aggies"],
    ["UTAH", "Utah Utes"],
    ["UTC", "Chattanooga Mocs"],
    ["UTEP", "UTEP Miners"],
    ["UTIC", "Utica Pioneers"],
    ["UTM", "UT Martin Skyhawks"],
    ["UTPB", "UT Permian Basin Falcons"],
    ["UTSA", "UTSA Roadrunners"],
    ["UTU", "Utah Tech Trailblazers"],
    ["UVA", "Virginia Cavaliers"],
    ["UVAW", "UVA Wise Cavaliers"],
    ["UWA", "West Alabama Tigers"],
    ["UWEC", "Wisconsin Eau Claire Blugolds"],
    ["UWF", "West Florida Argonauts"],
    ["UWL", "Wisconsin La Crosse Eagles"],
    ["UWO", "Wisconsin Oshkosh Titans"],
    ["UWP", "Wisconsin Platteville Pioneers"],
    ["UWRF", "Wisconsin River Falls Falcons"],
    ["UWSP", "Wisconsin Stevens Point Pointers"],
    ["UWST", "Wisconsin Stout Blue Devils"],
    ["UWW", "Wisconsin Whitewater Warhawks"],
    ["VAL", "Valparaiso Beacons"],
    ["VALD", "Valdosta State Blazers"],
    ["VAN", "Vanderbilt Commodores"],
    ["VCSU", "Valley City State Vikings"],
    ["VILL", "Villanova Wildcats"],
    ["VMI", "VMI Keydets"],
    ["VSU", "Virginia State Trojans"],
    ["VT", "Virginia Tech Hokies"],
    ["VTSC", "Vermont State Castleton Spartans"],
    ["VUL", "Virginia Lynchburg Dragons"],
    ["VUU", "Virginia Union Panthers"],
    ["W&J", "Washington & Jefferson Presidents"],
    ["W&L", "Washington and Lee Generals"],
    ["W&M", "William & Mary Tribe"],
    ["WAB", "Wabash Little Giants"],
    ["WAG", "Wagner Seahawks"],
    ["WAKE", "Wake Forest Demon Deacons"],
    ["WASH", "Washington Huskies"],
    ["WAYN", "Waynesburg Yellow Jackets"],
    ["WCHT", "West Chester Golden Rams"],
    ["WCIL", "Wheaton (IL) Thunder"],
    ["WCMO", "Westminster (MO) Blue Jays"],
    ["WCOH", "Wilmington (OH) Fightin' Quakers"],
    ["WCOL", "Western Colorado Mountaineers"],
    ["WCPA", "Westminster (PA) Titans"],
    ["WCSU", "Western Connecticut State Wolves"],
    ["WCU", "Western Carolina Catamounts"],
    ["WEB", "Weber State Wildcats"],
    ["WES", "Westgate Christian University Ravens"],
    ["WFST", "Westfield State Owls"],
    ["WGA", "West Georgia Wolves"],
    ["WHIW", "Whitworth Pirates"],
    ["WHLG", "Wheeling Cardinals"],
    ["WHTR", "Whittier Poets"],
    ["WIDE", "Widener Pride"],
    ["WILK", "Wilkes Colonels"],
    ["WINT", "Webber International Warriors"],
    ["WINU", "Wingate Bulldogs"],
    ["WIS", "Wisconsin Badgers"],
    ["WITT", "Wittenberg Tigers"],
    ["WIU", "Western Illinois Leathernecks"],
    ["WJC", "William Jewell Cardinals"],
    ["WKU", "Western Kentucky Hilltoppers"],
    ["WLC", "Wisconsin Lutheran Warriors"],
    ["WLDF", "Waldorf Warriors"],
    ["WLM", "Williams Ephs"],
    ["WLMT", "Willamette Bearcats"],
    ["WLSH", "Walsh Cavaliers"],
    ["WLU", "West Liberty Hilltoppers"],
    ["WLWD", "William Woods Owls"],
    ["WMSN", "Williamson Mechanics"],
    ["WMU", "Western Michigan Broncos"],
    ["WNE", "Western New England Golden Bears"],
    ["WNMU", "Western New Mexico Mustangs"],
    ["WNST", "Winona State Warriors"],
    ["WOF", "Wofford Terriers"],
    ["WOO", "Wooster Fighting Scots"],
    ["WORC", "Worcester State Lancers"],
    ["WORU", "Western Oregon Wolves"],
    ["WPEN", "William Penn Statesmen"],
    ["WPI", "WPI Engineers"],
    ["WPU", "William Paterson Pioneers"],
    ["WRNR", "Warner Royals"],
    ["WSBN", "Washburn Ichabods"],
    ["WSCT", "Wesleyan (CT) Cardinals"],
    ["WSMI", "Wayne State (MI) Warriors"],
    ["WSNE", "Wayne State (NE) Wildcats"],
    ["WSSU", "Winston-Salem State Rams"],
    ["WSU", "Washington State Cougars"],
    ["WTAM", "West Texas Buffaloes"],
    ["WTBG", "Wartburg Knights"],
    ["WUMO", "Washington St. Louis Bears"],
    ["WVSU", "West Virginia State Yellow Jackets"],
    ["WVU", "West Virginia Mountaineers"],
    ["WVUT", "WVU Tech Golden Bears"],
    ["WVWC", "West Virginia Wesleyan Bobcats"],
    ["WYBU", "Wayland Baptist Pioneers"],
    ["WYO", "Wyoming Cowboys"],
    ["YALE", "Yale Bulldogs"],
    ["YSU", "Youngstown State Penguins"]
  ],
  "NCAAB": [
    ["AAMU", "Alabama A&M Bulldogs"],
    ["ACU", "Abilene Christian Wildcats"],
    ["AF", "Air Force Falcons"],
    ["AKR", "Akron Zips"],
    ["ALA", "Alabama Crimson Tide"],
    ["ALCN", "Alcorn State Braves"],
    ["ALST", "Alabama State Hornets"],
    ["AMCC", "Texas A&M-Corpus Christi Islanders"],
    ["AMER", "American University Eagles"],
    ["APP", "App State Mountaineers"],
    ["APSU", "Austin Peay Governors"],
    ["ARIZ", "Arizona Wildcats"],
    ["ARK", "Arkansas Razorbacks"],
    ["ARMY", "Army Black Knights"],
    ["ARST", "Arkansas State Red Wolves"],
    ["ASU", "Arizona State Sun Devils"],
    ["AUB", "Auburn Tigers"],
    ["BALL", "Ball State Cardinals"],
    ["BAY", "Baylor Bears"],
    ["BC", "Boston College Eagles"],
    ["BCU", "Bethune-Cookman Wildcats"],
    ["BEL", "Belmont Bruins"],
    ["BELL", "Bellarmine Knights"],
    ["BGSU", "Bowling Green Falcons"],
    ["BING", "Binghamton Bearcats"],
    ["BOIS", "Boise State Broncos"],
    ["BRAD", "Bradley Braves"],
    ["BRWN", "Brown Bears"],
    ["BRY", "Bryant Bulldogs"],
    ["BTLR", "Butler Bulldogs"],
    ["BU", "Boston University Terriers"],
    ["BUCK", "Bucknell Bison"],
    ["BUF", "Buffalo Bulls"],
    ["BYU", "BYU Cougars"],
    ["CAL", "California Golden Bears"],
    ["CAM", "Campbell Fighting Camels"],
    ["CAN", "Canisius Golden Griffins"],
    ["CARK", "Central Arkansas Bears"],
    ["CBU", "California Baptist Lancers"],
    ["CCSU", "Central Connecticut Blue Devils"],
    ["CCU", "Coastal Carolina Chanticleers"],
    ["CHSO", "Charleston Southern Buccaneers"],
    ["CHST", "Chicago State Cougars"],
    ["CIN", "Cincinnati Bearcats"],
    ["CIT", "The Citadel Bulldogs"],
    ["CLE", "Cleveland State Vikings"],
    ["CLEM", "Clemson Tigers"],
    ["CLT", "Charlotte 49ers"],
    ["CMU", "Central Michigan Chippewas"],
    ["COFC", "Charleston Cougars"],
    ["COLG", "Colgate Raiders"],
    ["COLO", "Colorado Buffaloes"],
    ["COLU", "Columbia Lions"],
    ["CONN", "UConn Huskies"],
    ["COPP", "Coppin State Eagles"],
    ["COR", "Cornell Big Red"],
    ["CP", "Cal Poly Mustangs"],
    ["CREI", "Creighton Bluejays"],
    ["CSU", "Colorado State Rams"],
    ["CSUB", "Cal State Bakersfield Roadrunners"],
    ["CSUF", "Cal State Fullerton Titans"],
    ["CSUN", "Cal State Northridge Matadors"],
    ["DART", "Dartmouth Big Green"],
    ["DAV", "Davidson Wildcats"],
    ["DAY", "Dayton Flyers"],
    ["DEL", "Delaware Blue Hens"],
    ["DEN", "Denver Pioneers"],
    ["DEP", "DePaul Blue Demons"],
    ["DETM", "Detroit Mercy Titans"],
    ["DREX", "Drexel Dragons"],
    ["DRKE", "Drake Bulldogs"],
    ["DSU", "Delaware State Hornets"],
    ["DUKE", "Duke Blue Devils"],
    ["DUQ", "Duquesne Dukes"],
    ["ECU", "East Carolina Pirates"],
    ["EIU", "Eastern Illinois Panthers"],
    ["EKU", "Eastern Kentucky Colonels"],
    ["ELON", "Elon Phoenix"],
    ["EMU", "Eastern Michigan Eagles"],
    ["ETAM", "East Texas A&M Lions"],
    ["ETSU", "East Tennessee State Buccaneers"],
    ["EVAN", "Evansville Purple Aces"],
    ["EWU", "Eastern Washington Eagles"],
    ["FAIR", "Fairfield Stags"],
    ["FAMU", "Florida A&M Rattlers"],
    ["FAU", "Florida Atlantic Owls"],
    ["FDU", "Fairleigh Dickinson Knights"],
    ["FGCU", "Florida Gulf Coast Eagles"],
    ["FIU", "Florida International Panthers"],
    ["FLA", "Florida Gators"],
    ["FOR", "Fordham Rams"],
    ["FRES", "Fresno State Bulldogs"],
    ["FSU", "Florida State Seminoles"],
    ["FUR", "Furman Paladins"],
    ["GASO", "Georgia Southern Eagles"],
    ["GAST", "Georgia State Panthers"],
    ["GB", "Green Bay Phoenix"],
    ["GCU", "Grand Canyon Lopes"],
    ["GMU", "George Mason Patriots"],
    ["GONZ", "Gonzaga Bulldogs"],
    ["GRAM", "Grambling Tigers"],
    ["GT", "Georgia Tech Yellow Jackets"],
    ["GTWN", "Georgetown Hoyas"],
    ["GW", "George Washington Revolutionaries"],
    ["GWEB", "Gardner-Webb Runnin' Bulldogs"],
    ["HALL", "Seton Hall Pirates"],
    ["HAMP", "Hampton Pirates"],
    ["HARV", "Harvard Crimson"],
    ["HAW", "Hawai'i Rainbow Warriors"],
    ["HC", "Holy Cross Crusaders"],
    ["HCU", "Houston Christian Huskies"],
    ["HOF", "Hofstra Pride"],
    ["HOU", "Houston Cougars"],
    ["HOW", "Howard Bison"],
    ["HPU", "High Point Panthers"],
    ["IDHO", "Idaho Vandals"],
    ["IDST", "Idaho State Bengals"],
    ["ILL", "Illinois Fighting Illini"],
    ["ILST", "Illinois State Redbirds"],
    ["INST", "Indiana State Sycamores"],
    ["IONA", "Iona Gaels"],
    ["IOWA", "Iowa Hawkeyes"],
    ["ISU", "Iowa State Cyclones"],
    ["IU", "Indiana Hoosiers"],
    ["IUIN", "IU Indianapolis Jaguars"],
    ["JAX", "Jacksonville Dolphins"],
    ["JKST", "Jackson State Tigers"],
    ["JMU", "James Madison Dukes"],
    ["JOES", "Saint Joseph's Hawks"],
    ["JXST", "Jacksonville State Gamecocks"],
    ["KC", "Kansas City Roos"],
    ["KENN", "Kennesaw State Owls"],
    ["KENT", "Kent State Golden Flashes"],
    ["KSU", "Kansas State Wildcats"],
    ["KU", "Kansas Jayhawks"],
    ["L-MD", "Loyola Maryland Greyhounds"],
    ["LAF", "Lafayette Leopards"],
    ["LAM", "Lamar Cardinals"],
    ["LAS", "La Salle Explorers"],
    ["LBSU", "Long Beach State Beach"],
    ["LEH", "Lehigh Mountain Hawks"],
    ["LEM", "Le Moyne Dolphins"],
    ["LIB", "Liberty Flames"],
    ["LIP", "Lipscomb Bisons"],
    ["LIU", "Long Island University Sharks"],
    ["LMU", "Loyola Marymount Lions"],
    ["LONG", "Longwood Lancers"],
    ["LOU", "Louisville Cardinals"],
    ["LR", "Little Rock Trojans"],
    ["LSU", "LSU Tigers"],
    ["LT", "Louisiana Tech Bulldogs"],
    ["LUC", "Loyola Chicago Ramblers"],
    ["M-OH", "Miami (OH) RedHawks"],
    ["MAN", "Manhattan Jaspers"],
    ["MARQ", "Marquette Golden Eagles"],
    ["MASS", "Massachusetts Minutemen"],
    ["MCN", "McNeese Cowboys"],
    ["MD", "Maryland Terrapins"],
    ["ME", "Maine Black Bears"],
    ["MEM", "Memphis Tigers"],
    ["MER", "Mercer Bears"],
    ["MERC", "Mercyhurst Lakers"],
    ["MIA", "Miami Hurricanes"],
    ["MICH", "Michigan Wolverines"],
    ["MILW", "Milwaukee Panthers"],
    ["MINN", "Minnesota Golden Gophers"],
    ["MISS", "Ole Miss Rebels"],
    ["MIZ", "Missouri Tigers"],
    ["MONM", "Monmouth Hawks"],
    ["MONT", "Montana Grizzlies"],
    ["MORE", "Morehead State Eagles"],
    ["MORG", "Morgan State Bears"],
    ["MOST", "Missouri State Bears"],
    ["MRMK", "Merrimack Warriors"],
    ["MRSH", "Marshall Thundering Herd"],
    ["MRST", "Marist Red Foxes"],
    ["MSM", "Mount St. Mary's Mountaineers"],
    ["MSST", "Mississippi State Bulldogs"],
    ["MSU", "Michigan State Spartans"],
    ["MTST", "Montana State Bobcats"],
    ["MTSU", "Middle Tennessee Blue Raiders"],
    ["MUR", "Murray State Racers"],
    ["MVSU", "Mississippi Valley State Delta Devils"],
    ["NAU", "Northern Arizona Lumberjacks"],
    ["NAVY", "Navy Midshipmen"],
    ["NCAT", "North Carolina A&T Aggies"],
    ["NCCU", "North Carolina Central Eagles"],
    ["NCSU", "NC State Wolfpack"],
    ["ND", "Notre Dame Fighting Irish"],
    ["NDSU", "North Dakota State Bison"],
    ["NE", "Northeastern Huskies"],
    ["NEB", "Nebraska Cornhuskers"],
    ["NEV", "Nevada Wolf Pack"],
    ["NHVN", "New Haven Chargers"],
    ["NIA", "Niagara Purple Eagles"],
    ["NICH", "Nicholls Colonels"],
    ["NIU", "Northern Illinois Huskies"],
    ["NJIT", "NJIT Highlanders"],
    ["NKU", "Northern Kentucky Norse"],
    ["NMSU", "New Mexico State Aggies"],
    ["NOLA", "LSU New Orleans Privateers"],
    ["NORF", "Norfolk State Spartans"],
    ["NU", "Northwestern Wildcats"],
    ["NWST", "Northwestern State Demons"],
    ["OAK", "Oakland Golden Grizzlies"],
    ["ODU", "Old Dominion Monarchs"],
    ["OHIO", "Ohio Bobcats"],
    ["OKST", "Oklahoma State Cowboys"],
    ["OMA", "Omaha Mavericks"],
    ["ORE", "Oregon Ducks"],
    ["ORST", "Oregon State Beavers"],
    ["ORU", "Oral Roberts Golden Eagles"],
    ["OSU", "Ohio State Buckeyes"],
    ["OU", "Oklahoma Sooners"],
    ["PAC", "Pacific Tigers"],
    ["PENN", "Pennsylvania Quakers"],
    ["PEPP", "Pepperdine Waves"],
    ["PFW", "Purdue Fort Wayne Mastodons"],
    ["PITT", "Pittsburgh Panthers"],
    ["PORT", "Portland Pilots"],
    ["PRES", "Presbyterian Blue Hose"],
    ["PRIN", "Princeton Tigers"],
    ["PROV", "Providence Friars"],
    ["PRST", "Portland State Vikings"],
    ["PSU", "Penn State Nittany Lions"],
    ["PUR", "Purdue Boilermakers"],
    ["PV", "Prairie View A&M Panthers"],
    ["QUIN", "Quinnipiac Bobcats"],
    ["RAD", "Radford Highlanders"],
    ["RGV", "UT Rio Grande Valley Vaqueros"],
    ["RICE", "Rice Owls"],
    ["RICH", "Richmond Spiders"],
    ["RID", "Rider Broncs"],
    ["RMU", "Robert Morris Colonials"],
    ["RUTG", "Rutgers Scarlet Knights"],
    ["SAC", "Sacramento State Hornets"],
    ["SAM", "Samford Bulldogs"],
    ["SBU", "St. Bonaventure Bonnies"],
    ["SC", "South Carolina Gamecocks"],
    ["SCST", "South Carolina State Bulldogs"],
    ["SCU", "Santa Clara Broncos"],
    ["SDAK", "South Dakota Coyotes"],
    ["SDST", "South Dakota State Jackrabbits"],
    ["SDSU", "San Diego State Aztecs"],
    ["SEA", "Seattle U Redhawks"],
    ["SELA", "SE Louisiana Lions"],
    ["SEMO", "Southeast Missouri State Redhawks"],
    ["SF", "San Francisco Dons"],
    ["SFA", "Stephen F. Austin Lumberjacks"],
    ["SHSU", "Sam Houston Bearkats"],
    ["SHU", "Sacred Heart Pioneers"],
    ["SIE", "Siena Saints"],
    ["SIU", "Southern Illinois Salukis"],
    ["SIUE", "SIU Edwardsville Cougars"],
    ["SJSU", "San José State Spartans"],
    ["SJU", "St. John's Red Storm"],
    ["SLU", "Saint Louis Billikens"],
    ["SMC", "Saint Mary's Gaels"],
    ["SMU", "SMU Mustangs"],
    ["SOU", "Southern Jaguars"],
    ["SPU", "Saint Peter's Peacocks"],
    ["STAN", "Stanford Cardinal"],
    ["STBK", "Stony Brook Seawolves"],
    ["STET", "Stetson Hatters"],
    ["STMN", "St. Thomas Tommies"],
    ["STO", "Stonehill Skyhawks"],
    ["SUU", "Southern Utah Thunderbirds"],
    ["SYR", "Syracuse Orange"],
    ["TA&M", "Texas A&M Aggies"],
    ["TAR", "Tarleton State Texans"],
    ["TCU", "TCU Horned Frogs"],
    ["TEM", "Temple Owls"],
    ["TENN", "Tennessee Volunteers"],
    ["TEX", "Texas Longhorns"],
    ["TLSA", "Tulsa Golden Hurricane"],
    ["TNST", "Tennessee State Tigers"],
    ["TNTC", "Tennessee Tech Golden Eagles"],
    ["TOL", "Toledo Rockets"],
    ["TOW", "Towson Tigers"],
    ["TROY", "Troy Trojans"],
    ["TTU", "Texas Tech Red Raiders"],
    ["TULN", "Tulane Green Wave"],
    ["TXSO", "Texas Southern Tigers"],
    ["TXST", "Texas State Bobcats"],
    ["UAB", "UAB Blazers"],
    ["UALB", "UAlbany Great Danes"],
    ["UAPB", "Arkansas-Pine Bluff Golden Lions"],
    ["UCD", "UC Davis Aggies"],
    ["UCF", "UCF Knights"],
    ["UCI", "UC Irvine Anteaters"],
    ["UCLA", "UCLA Bruins"],
    ["UCR", "UC Riverside Highlanders"],
    ["UCSB", "UC Santa Barbara Gauchos"],
    ["UCSD", "UC San Diego Tritons"],
    ["UGA", "Georgia Bulldogs"],
    ["UIC", "UIC Flames"],
    ["UIW", "Incarnate Word Cardinals"],
    ["UK", "Kentucky Wildcats"],
    ["UL", "Louisiana Ragin' Cajuns"],
    ["ULM", "UL Monroe Warhawks"],
    ["UMBC", "UMBC Retrievers"],
    ["UMES", "Maryland Eastern Shore Hawks"],
    ["UML", "UMass Lowell River Hawks"],
    ["UNA", "North Alabama Lions"],
    ["UNC", "North Carolina Tar Heels"],
    ["UNCA", "UNC Asheville Bulldogs"],
    ["UNCG", "UNC Greensboro Spartans"],
    ["UNCO", "Northern Colorado Bears"],
    ["UNCW", "UNC Wilmington Seahawks"],
    ["UND", "North Dakota Fighting Hawks"],
    ["UNF", "North Florida Ospreys"],
    ["UNH", "New Hampshire Wildcats"],
    ["UNI", "Northern Iowa Panthers"],
    ["UNLV", "UNLV Rebels"],
    ["UNM", "New Mexico Lobos"],
    ["UNT", "North Texas Mean Green"],
    ["UPST", "South Carolina Upstate Spartans"],
    ["URI", "Rhode Island Rams"],
    ["USA", "South Alabama Jaguars"],
    ["USC", "USC Trojans"],
    ["USD", "San Diego Toreros"],
    ["USF", "South Florida Bulls"],
    ["USM", "Southern Miss Golden Eagles"],
    ["USU", "Utah State Aggies"],
    ["UTA", "UT Arlington Mavericks"],
    ["UTAH", "Utah Utes"],
    ["UTC", "Chattanooga Mocs"],
    ["UTEP", "UTEP Miners"],
    ["UTM", "UT Martin Skyhawks"],
    ["UTSA", "UTSA Roadrunners"],
    ["UTU", "Utah Tech Trailblazers"],
    ["UVA", "Virginia Cavaliers"],
    ["UVM", "Vermont Catamounts"],
    ["UVU", "Utah Valley Wolverines"],
    ["UWF", "West Florida Argonauts"],
    ["VAL", "Valparaiso Beacons"],
    ["VAN", "Vanderbilt Commodores"],
    ["VCU", "VCU Rams"],
    ["VILL", "Villanova Wildcats"],
    ["VMI", "VMI Keydets"],
    ["VT", "Virginia Tech Hokies"],
    ["W&M", "William & Mary Tribe"],
    ["WAG", "Wagner Seahawks"],
    ["WAKE", "Wake Forest Demon Deacons"],
    ["WASH", "Washington Huskies"],
    ["WCU", "Western Carolina Catamounts"],
    ["WEB", "Weber State Wildcats"],
    ["WGA", "West Georgia Wolves"],
    ["WICH", "Wichita State Shockers"],
    ["WIN", "Winthrop Eagles"],
    ["WIS", "Wisconsin Badgers"],
    ["WIU", "Western Illinois Leathernecks"],
    ["WKU", "Western Kentucky Hilltoppers"],
    ["WMU", "Western Michigan Broncos"],
    ["WOF", "Wofford Terriers"],
    ["WRST", "Wright State Raiders"],
    ["WSU", "Washington State Cougars"],
    ["WVU", "West Virginia Mountaineers"],
    ["WYO", "Wyoming Cowboys"],
    ["XAV", "Xavier Musketeers"],
    ["YALE", "Yale Bulldogs"],
    ["YSU", "Youngstown State Penguins"]
  ],
  "MLS": [
    ["ATL", "Atlanta United FC"],
    ["ATX", "Austin FC"],
    ["CHI", "Chicago Fire FC"],
    ["CIN", "FC Cincinnati"],
    ["CLB", "Columbus Crew"],
    ["CLT", "Charlotte FC"],
    ["COL", "Colorado Rapids"],
    ["DAL", "FC Dallas"],
    ["DC", "D.C. United"],
    ["HOU", "Houston Dynamo FC"],
    ["LA", "LA Galaxy"],
    ["LAFC", "LAFC"],
    ["MIA", "Inter Miami CF"],
    ["MIN", "Minnesota United FC"],
    ["MTL", "CF Montréal"],
    ["NE", "New England Revolution"],
    ["NSH", "Nashville SC"],
    ["NYC", "New York City FC"],
    ["ORL", "Orlando City SC"],
    ["PHI", "Philadelphia Union"],
    ["POR", "Portland Timbers"],
    ["RBNY", "Red Bull New York"],
    ["RSL", "Real Salt Lake"],
    ["SD", "San Diego FC"],
    ["SEA", "Seattle Sounders FC"],
    ["SJ", "San Jose Earthquakes"],
    ["SKC", "Sporting Kansas City"],
    ["STL", "St. Louis CITY SC"],
    ["TOR", "Toronto FC"],
    ["VAN", "Vancouver Whitecaps"]
  ],
  "EPL": [
    ["ARS", "Arsenal"],
    ["AVL", "Aston Villa"],
    ["BHA", "Brighton & Hove Albion"],
    ["BOU", "AFC Bournemouth"],
    ["BRE", "Brentford"],
    ["CHE", "Chelsea"],
    ["COV", "Coventry City"],
    ["CRY", "Crystal Palace"],
    ["EVE", "Everton"],
    ["FUL", "Fulham"],
    ["HUL", "Hull City"],
    ["IPS", "Ipswich Town"],
    ["LEE", "Leeds United"],
    ["LIV", "Liverpool"],
    ["MAN", "Manchester United"],
    ["MNC", "Manchester City"],
    ["NEW", "Newcastle United"],
    ["NFO", "Nottingham Forest"],
    ["SUN", "Sunderland"],
    ["TOT", "Tottenham Hotspur"]
  ],
  "UCL": [
    ["AEK", "AEK Athens"],
    ["ARS", "Arsenal"],
    ["ATM", "Atlético Madrid"],
    ["AVL", "Aston Villa"],
    ["BAR", "Barcelona"],
    ["BET", "Real Betis"],
    ["BODO", "Bodo/Glimt"],
    ["BRU", "Club Brugge"],
    ["COMO", "Como"],
    ["DOR", "Borussia Dortmund"],
    ["FCP", "FC Porto"],
    ["FEN", "Fenerbahce"],
    ["FEY", "Feyenoord Rotterdam"],
    ["GAL", "Galatasaray"],
    ["INT", "Internazionale"],
    ["LAS", "LASK Linz"],
    ["LILL", "Lille"],
    ["LIV", "Liverpool"],
    ["MAN", "Manchester United"],
    ["MNC", "Manchester City"],
    ["MUN", "Bayern Munich"],
    ["NAP", "Napoli"],
    ["PSG", "Paris Saint-Germain"],
    ["PSV", "PSV Eindhoven"],
    ["RBL", "RB Leipzig"],
    ["RCL", "Lens"],
    ["RMA", "Real Madrid"],
    ["ROMA", "AS Roma"],
    ["SAB", "Sabah FK"],
    ["SCP", "Sporting CP"],
    ["SHK", "Shakhtar Donetsk"],
    ["SLB", "Slovan Bratislava"],
    ["SLP", "Slavia Prague"],
    ["VFB", "VfB Stuttgart"],
    ["VIK", "Viking FK"],
    ["VIL", "Villarreal"]
  ]
};
