import { fetchAllPublicProps } from './public-feeds.mjs';
import { fetchEspnGameLog, resolveEspnAthleteId } from './espn-game-logs.mjs';
import { persistActiveProps, persistGameLogs, activePlayersForHistory, publicPersistenceConfigured } from './public-persistence.mjs';

const state={running:false,lastPropsAt:null,lastHistoryAt:null,lastError:null,providers:{},propsWritten:0,logsWritten:0,timer:null,historyTimer:null};
const minutes=()=>Math.max(2,Math.min(3,Number(process.env.AUTOSCOUT_PUBLIC_PROP_INTERVAL_MINUTES||3)));
export function publicIngestHealth(){return{enabled:true,zeroCost:true,authenticatedExternalApis:false,intervalMinutes:minutes(),...state,timer:undefined,historyTimer:undefined,databaseConfigured:publicPersistenceConfigured()};}
async function propsTick(){if(!publicPersistenceConfigured())return;try{const result=await fetchAllPublicProps();state.providers=result.providers;state.propsWritten=await persistActiveProps(result.rows);state.lastPropsAt=new Date().toISOString();state.lastError=null;console.log(`[public-ingest] props=${state.propsWritten} pp=${result.providers.prizepicks?.count||0} ud=${result.providers.underdog?.count||0} dk=${result.providers.draftkings?.count||0}`);}catch(e){state.lastError=String(e?.message||e).slice(0,180);console.error('[public-ingest] prop cycle failed',state.lastError);}}
async function historyTick(){if(!publicPersistenceConfigured())return;try{const players=await activePlayersForHistory({limit:120});let written=0;for(const p of players){let espnId=/^\d+$/.test(String(p.player_id))?String(p.player_id):null;if(!espnId&&p.player_name)espnId=await resolveEspnAthleteId({name:p.player_name,sport:p.sport});if(!espnId)continue;for(const seasonType of [2,3]){try{const logs=await fetchEspnGameLog({sport:p.sport,playerId:espnId,season:new Date().getUTCFullYear(),seasonType});if(logs.length)written+=await persistGameLogs(logs);}catch{}}}state.logsWritten=written;state.lastHistoryAt=new Date().toISOString();}catch(e){state.lastError=String(e?.message||e).slice(0,180);console.error('[public-ingest] history cycle failed',state.lastError);}}
export function startPublicIngestWorker(){if(state.running)return state.timer;state.running=true;if(!publicPersistenceConfigured()){console.log('[public-ingest] database not configured; worker idle');return null;}const period=minutes()*60_000;state.timer=setInterval(()=>void propsTick(),period);state.timer.unref?.();state.historyTimer=setInterval(()=>void historyTick(),6*60*60_000);state.historyTimer.unref?.();setTimeout(()=>void propsTick(),5000).unref?.();setTimeout(()=>void historyTick(),45_000).unref?.();console.log(`[public-ingest] zero-cost feeds enabled every ${minutes()}m; ESPN history every 6h`);return state.timer;}
export function stopPublicIngestWorker(){if(state.timer)clearInterval(state.timer);if(state.historyTimer)clearInterval(state.historyTimer);state.timer=null;state.historyTimer=null;state.running=false;}
