// Lightweight ensemble trainer for ObligeProps structured prop data.
// No provider calls. Consumes leakage-safe rows from training-dataset.mjs.
// Ridge is the first production-capable learner; tree/NN slots remain explicit
// challengers until their runtime dependencies and validation artifacts exist.

const finite=v=>typeof v==='number'&&Number.isFinite(v);
const FEATURE_KEYS=Object.freeze(['l5Mean','l10Mean','l20Mean','seasonMean','l5OverRate','l10OverRate','l20OverRate','h2hMean','h2hOverRate','h2hGames','historyGames','isHome','restDays','opponentDefenseRank','marketOverProbability']);
function solve(A,b){const n=b.length,M=A.map((r,i)=>[...r,b[i]]);for(let i=0;i<n;i++){let p=i;for(let r=i+1;r<n;r++)if(Math.abs(M[r][i])>Math.abs(M[p][i]))p=r;[M[i],M[p]]=[M[p],M[i]];if(Math.abs(M[i][i])<1e-10)return null;for(let r=i+1;r<n;r++){const f=M[r][i]/M[i][i];for(let c=i;c<=n;c++)M[r][c]-=f*M[i][c];}}const x=Array(n).fill(0);for(let i=n-1;i>=0;i--){let s=M[i][n];for(let c=i+1;c<n;c++)s-=M[i][c]*x[c];x[i]=s/M[i][i];}return x;}
function matrix(rows){const means={},scales={};for(const k of FEATURE_KEYS){const vals=rows.map(r=>r.features?.[k]).filter(finite);means[k]=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;const variance=vals.length>1?vals.reduce((s,v)=>s+(v-means[k])**2,0)/(vals.length-1):0;scales[k]=Math.sqrt(variance)||1;}const x=rows.map(r=>[1,...FEATURE_KEYS.map(k=>finite(r.features?.[k])?(r.features[k]-means[k])/scales[k]:0)]);return{x,means,scales};}
export function trainRidge(rows=[],{lambda=3}={}){if(!Array.isArray(rows)||rows.length<20)return null;const {x,means,scales}=matrix(rows),k=x[0].length,A=Array.from({length:k},()=>Array(k).fill(0)),b=Array(k).fill(0);for(let i=0;i<rows.length;i++){for(let a=0;a<k;a++){b[a]+=x[i][a]*rows[i].actual;for(let c=0;c<k;c++)A[a][c]+=x[i][a]*x[i][c];}}for(let i=1;i<k;i++)A[i][i]+=lambda;const coefficients=solve(A,b);return coefficients?{type:'ridge',version:1,featureKeys:[...FEATURE_KEYS],means,scales,coefficients,trainedRows:rows.length}:null;}
export function predictRidge(model,row){if(!model?.coefficients)return null;const x=[1,...model.featureKeys.map(k=>finite(row.features?.[k])?(row.features[k]-model.means[k])/model.scales[k]:0)];return x.reduce((s,v,i)=>s+v*model.coefficients[i],0);}
export function walkForwardTrain(rows=[],{minTrain=20,step=1,lambda=3}={}){const sorted=[...rows].sort((a,b)=>Date.parse(a.gameStartTime)-Date.parse(b.gameStartTime)),predictions=[];for(let i=minTrain;i<sorted.length;i+=step){const train=sorted.slice(0,i),model=trainRidge(train,{lambda});if(!model)continue;for(const row of sorted.slice(i,Math.min(sorted.length,i+step))){const projection=predictRidge(model,row);if(finite(projection))predictions.push({...row,projection,trainedThrough:train.at(-1).gameStartTime});}}return predictions;}
export const ENSEMBLE_SLOTS=Object.freeze({ridge:'ready',boostedTree:'pending-runtime',neuralNetwork:'pending-runtime'});
